'use client';
import { useState } from 'react';
import { Download, ExternalLink, Copy } from 'lucide-react';
import { fullLogoSVG, sitePages, cityPages, projectImages } from './asset-data';
const colors = [{ name: 'Navy', hex: '#1e293b' }, { name: 'Gold', hex: '#eab308' }, { name: 'Slate', hex: '#64748b' }, { name: 'Hell', hex: '#f8fafc' }];
function saveBlob(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 10000); }
export default function Assets() {
  const [folder, setFolder] = useState(projectImages[0]?.folder || ''); const [copied, setCopied] = useState(''); const [error, setError] = useState('');
  const png = () => { const url = URL.createObjectURL(new Blob([fullLogoSVG], { type: 'image/svg+xml' })); const image = new window.Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = 1200; canvas.height = 360; canvas.getContext('2d')?.drawImage(image, 0, 0, 1200, 360); canvas.toBlob(blob => { if (blob) saveBlob(blob, 'rd-frankenbau-logo.png'); URL.revokeObjectURL(url); }, 'image/png'); }; image.onerror = () => { URL.revokeObjectURL(url); setError('PNG konnte nicht erstellt werden. Bitte SVG verwenden.'); }; image.src = url; };
  return <div className="rd-flow">{error && <p className="rd-alert rd-error" role="alert">{error}</p>}<section className="rd-panel"><div className="rd-section-heading"><div><h2>Logo & Farben</h2><p>Die bestehende Identität Ihrer Website.</p></div></div><div className="rd-brand-assets"><div className="rd-logo-preview"><img src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(fullLogoSVG)}`} alt="RD Bau Franken Logo" /><div className="rd-actions"><button className="rd-button rd-secondary" onClick={() => saveBlob(new Blob([fullLogoSVG], { type: 'image/svg+xml' }), 'rd-frankenbau-logo.svg')}><Download size={17} />SVG</button><button className="rd-button rd-secondary" onClick={png}><Download size={17} />PNG</button></div></div><div className="rd-swatches">{colors.map(c => <button key={c.hex} onClick={async () => { try { await navigator.clipboard.writeText(c.hex); setCopied(c.hex); } catch { setError('Kopieren nicht möglich. Farbcode: ' + c.hex); } }}><span style={{ background: c.hex }} /><strong>{c.name}</strong><small>{copied === c.hex ? 'Kopiert' : c.hex}</small><Copy size={14} /></button>)}</div></div></section>
    <section className="rd-panel"><div className="rd-section-heading"><div><h2>Projektbilder</h2><p>Vorher und nachher – nach Projekt sortiert.</p></div></div><label className="rd-field rd-search">Projekt auswählen<select value={folder} onChange={e => setFolder(e.target.value)}>{Array.from(new Set(projectImages.map(i => i.folder))).map(f => <option key={f}>{f}</option>)}</select></label><div className="rd-image-grid">{projectImages.filter(i => i.folder === folder).map((item, index) => <a key={item.path} className="rd-image-card" href={item.path} download><img src={item.path} alt={`${item.folder}, Bild ${index + 1}`} loading="lazy" /><span>Bild {index + 1}<Download size={17} /></span></a>)}</div></section>
    <section className="rd-panel"><div className="rd-section-heading"><div><h2>Seiten Ihrer Website</h2><p>Direkt öffnen und prüfen.</p></div></div><div className="rd-site-links">{[...sitePages, ...cityPages].map(p => <a key={p.path} href={p.path} target="_blank" rel="noreferrer">{p.name}<ExternalLink size={15} /></a>)}</div></section>
  </div>;
}
