'use client';
import { useRef, useState } from 'react';
import { Copy, Download, FileText, Plus, RefreshCw } from 'lucide-react';
import { Quote, quoteNumber, dateDE, money } from '@/lib/quotes/model';
import { adminApi, message } from './api';
export async function downloadOffer(quote: Quote, eventId: string) {
  const response = await fetch(`/api/admin/quotes/${quote.id}/pdf`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ eventId }) });
  if (!response.ok) { if (response.status === 401) window.dispatchEvent(new Event('rd-session-expired')); const data = await response.json(); throw new Error(data.error || 'PDF konnte nicht geladen werden.'); }
  const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = `${quoteNumber(quote)}.pdf`; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 60000);
  return response.headers.get('X-Sheet-Synced') === 'true';
}
type Props = { quotes: Quote[]; hasMore: boolean; onUpdate: (q: Quote) => void; onRefresh: () => Promise<void>; onMore: () => Promise<void>; onNew: () => void; onCopy: (q: Quote) => void };
export function Offers({ quotes, hasMore, onUpdate, onRefresh, onMore, onNew, onCopy }: Props) {
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState('alle'); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const eventIds = useRef<Record<string, string>>({});
  const filtered = quotes.filter(q => (filter === 'alle' || q.status === filter) && `${q.snapshot.customer.name} ${q.snapshot.project} ${quoteNumber(q)}`.toLowerCase().includes(search.toLowerCase()));
  async function run(id: string, action: () => Promise<void>) { setBusy(id); setError(''); setNotice(''); try { await action(); } catch (e) { setError(message(e)); } finally { setBusy(''); } }
  return <div className="rd-flow"><div className="rd-offer-toolbar"><label className="rd-field">Angebote suchen<input type="search" placeholder="Kunde, Projekt oder Nummer" value={search} onChange={e => setSearch(e.target.value)} /></label><label className="rd-field">Status<select value={filter} onChange={e => setFilter(e.target.value)}><option value="alle">Alle Angebote</option>{['offen', 'angenommen', 'abgelehnt', 'archiviert'].map(s => <option key={s} value={s}>{s[0].toUpperCase() + s.slice(1)}</option>)}</select></label><button className="rd-icon-button" aria-label="Angebote neu laden" disabled={Boolean(busy)} onClick={() => void run('refresh', onRefresh)}><RefreshCw size={19} /></button><button className="rd-button rd-primary" onClick={onNew}><Plus size={18} />Angebot erstellen</button></div>
    {error && <p className="rd-alert rd-error" role="alert">{error}</p>}{notice && <p className="rd-alert rd-success" role="status">{notice}</p>}
    {filtered.length === 0 && <div className="rd-panel rd-empty"><FileText size={35} /><h2>{quotes.length ? 'Keine passenden Angebote' : 'Platz für Ihr erstes Angebot'}</h2><p>{quotes.length ? 'Passen Sie Suche oder Statusfilter an.' : 'Erstellen Sie eine Berechnung und speichern Sie sie. Hier finden Sie später alle PDFs wieder.'}</p><button className="rd-button rd-secondary" onClick={onNew}>Zum Rechner</button></div>}
    {filtered.map(q => <article className="rd-panel rd-offer" key={q.id}><div className="rd-offer-top"><div><span className="rd-eyebrow">{quoteNumber(q)} · {dateDE(q.created_at)}</span><h2>{q.snapshot.customer.name}</h2><p>{q.snapshot.project}</p></div><strong className="rd-offer-total">{money(q.snapshot.totalCents)}</strong></div><details className="rd-details"><summary>Positionen ansehen <span>{q.snapshot.lines.length} Leistungen</span></summary><div className="rd-saved-lines">{q.snapshot.lines.map(l => <div key={l.serviceId}><span>{l.name}<small>{l.quantity} {l.unit} × {money(l.priceCents)} netto</small></span><strong>{money(l.totalCents)}</strong></div>)}</div></details><div className="rd-offer-bottom"><label className="rd-field rd-status-select"><span className="rd-sr-only">Status {quoteNumber(q)}</span><select value={q.status} disabled={Boolean(busy)} onChange={e => void run(q.id, async () => { const data = await adminApi<{ quote: Quote }>(`/api/admin/quotes/${q.id}`, { method: 'PATCH', body: JSON.stringify({ status: e.target.value, version: q.version }) }); onUpdate(data.quote); })}>{['offen', 'angenommen', 'abgelehnt', 'archiviert'].map(s => <option key={s} value={s}>{s[0].toUpperCase() + s.slice(1)}</option>)}</select></label><span className={`rd-sync-label ${q.sheet_synced_version >= q.version ? 'synced' : ''}`}>{q.sheet_synced_version >= q.version ? 'Im Sheet erfasst' : 'Sheet ausstehend'}<small>{q.pdf_count} PDF-Abruf{q.pdf_count !== 1 ? 'e' : ''}</small></span><div className="rd-offer-actions"><button className="rd-button rd-secondary" disabled={Boolean(busy)} onClick={() => onCopy(q)}><Copy size={17} />Kopie</button><button className="rd-button rd-primary" disabled={Boolean(busy)} onClick={() => void run(q.id, async () => { eventIds.current[q.id] ||= crypto.randomUUID(); const synced = await downloadOffer(q, eventIds.current[q.id]); delete eventIds.current[q.id]; setNotice(synced ? 'PDF bereitgestellt und im Sheet erfasst.' : 'PDF bereitgestellt. Übertragung an das Sheet steht aus.'); await onRefresh(); })}><Download size={17} />{busy === q.id ? 'Bitte warten …' : 'PDF'}</button></div></div></article>)}
    {hasMore && <div className="rd-load-more"><p>Die Suche umfasst die geladenen Angebote. Weitere Angebote nachladen, um auch ältere zu durchsuchen.</p><button className="rd-button rd-secondary" disabled={Boolean(busy)} onClick={() => void run('more', onMore)}>Weitere Angebote laden</button></div>}
  </div>;
}
