'use client';
import { useState } from 'react';
import { Check, ChevronDown, Plus, Save } from 'lucide-react';
import { MAX_SERVICES, Service, Settings, settingsSchema, units } from '@/lib/quotes/model';
import { matchesService, serviceCategories, serviceCategory } from '@/lib/quotes/catalogue';
import { adminApi, message } from './api';
type Props = { settings: Settings; version: number; ready: boolean; onDirty: (v: boolean) => void; onSaved: (s: Settings, v: number) => void };
export function SettingsForm({ settings, version, ready, onDirty, onSaved }: Props) {
  const [form, setForm] = useState(settings); const [prices, setPrices] = useState<Record<string, string>>(() => Object.fromEntries(settings.services.map(s => [s.id, s.priceCents === null ? '' : (s.priceCents / 100).toFixed(2).replace('.', ',')])));
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(false); const [search, setSearch] = useState('');
  const [category, setCategory] = useState(''); const [visibleCount, setVisibleCount] = useState(12);
  const change = (patch: Partial<Settings>) => { setForm(f => ({ ...f, ...patch })); onDirty(true); setSuccess(false); };
  const changeService = (id: string, patch: Partial<Service>) => change({ services: form.services.map(s => s.id === id ? { ...s, ...patch } : s) });
  const categories = serviceCategories(form.services);
  const matching = form.services.filter(s => matchesService(s, search, category));
  return <form className="rd-flow" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); setSuccess(false); try {
    const next = { ...form, services: form.services.map(s => { const value = (prices[s.id] || '').trim(); if (value && !/^\d{1,7}([.,]\d{1,2})?$/.test(value)) throw new Error(`Preis für „${s.name}“ prüfen. Beispiel: 24,50 (ohne Tausenderpunkt).`); return { ...s, priceCents: value ? Math.round(Number(value.replace(',', '.')) * 100) : null }; }) };
    if (next.taxPercent !== 0) next.taxNote = '';
    const parsed = settingsSchema.safeParse(next); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message || 'Eingaben prüfen.');
    if (next.taxPercent === 0 && !next.taxNote.trim()) throw new Error('Bei 0 % MwSt. bitte einen Steuerhinweis eingeben.');
    const result = await adminApi<{ settings: Settings; version: number }>('/api/admin/settings', { method: 'PUT', body: JSON.stringify({ settings: parsed.data, version }) });
    setForm(result.settings); onSaved(result.settings, result.version); setSuccess(true);
  } catch (e) { setError(message(e)); } finally { setBusy(false); } }}>
    <fieldset disabled={busy} className="rd-panel"><div className="rd-section-heading"><div><h2>Leistungen & Preise</h2><p>Alle Einzelpreise netto. Ein leeres Preisfeld bedeutet „noch nicht festgelegt“.</p></div></div>
      <div className="rd-catalog-toolbar"><label className="rd-field">Leistung finden<input type="search" placeholder="Bezeichnung oder Positionsnummer" value={search} onChange={e => { setSearch(e.target.value); setVisibleCount(12); }} /></label><label className="rd-field">Bereich<select value={category} onChange={e => { setCategory(e.target.value); setVisibleCount(12); }}><option value="">Alle Bereiche</option>{categories.map(c => <option key={c}>{c}</option>)}</select></label></div>
      <p className="rd-catalog-count">{matching.length} Leistungen · {form.services.filter(s => s.active).length} aktiv</p>
      <div className="rd-catalog">{matching.slice(0, visibleCount).map(s => <div key={s.id} className="rd-catalog-row" role="group" aria-label={`Leistung ${s.catalogNumber || s.name}`}>
        <label className="rd-field">{s.catalogNumber ? `Position ${s.catalogNumber}` : 'Leistung'}<input value={s.name} maxLength={90} onChange={e => changeService(s.id, { name: e.target.value })} /></label>
        <label className="rd-field">Einheit<select value={s.unit} onChange={e => changeService(s.id, { unit: e.target.value as typeof s.unit })}>{units.map(u => <option key={u}>{u}</option>)}</select></label>
        <label className="rd-field">Preis netto (€)<input inputMode="decimal" placeholder="Nicht festgelegt" value={prices[s.id] || ''} onChange={e => { setPrices(p => ({ ...p, [s.id]: e.target.value })); onDirty(true); setSuccess(false); }} /></label>
        <label className="rd-check-field"><input type="checkbox" checked={s.active} onChange={e => changeService(s.id, { active: e.target.checked })} /><span>Aktiv</span></label>
        <details className="rd-catalog-details"><summary>Leistungsumfang & Details{ s.internalNote && <span>Hinweis vorhanden</span>}</summary><div className="rd-fields">
          <label className="rd-field">Bereich<select value={serviceCategory(s)} onChange={e => changeService(s.id, { category: e.target.value })}>{[...new Set(['Eigene Leistungen', ...categories])].map(c => <option key={c}>{c}</option>)}</select></label>
          <label className="rd-field">Vorgabemenge<input type="number" inputMode="decimal" min="0.001" max="100000" step="0.001" value={s.defaultQuantity ?? 1} onChange={e => changeService(s.id, { defaultQuantity: e.target.value === '' ? NaN : Number(e.target.value) })} /></label>
          <label className="rd-field rd-span">Leistungsbeschreibung im PDF<textarea rows={3} maxLength={1000} value={s.description || ''} onChange={e => changeService(s.id, { description: e.target.value })} placeholder="Optional: genauer Umfang, Materialien und Maße" /></label>
          <label className="rd-field rd-span">Interner Hinweis<textarea rows={2} maxLength={600} value={s.internalNote || ''} onChange={e => changeService(s.id, { internalNote: e.target.value })} placeholder="Nur für Sie sichtbar" /></label>
        </div></details>
      </div>)}</div>
      {matching.length > visibleCount && <button type="button" className="rd-text-link rd-full" onClick={() => setVisibleCount(n => n + 12)}>Weitere Leistungen anzeigen ({Math.min(visibleCount, matching.length)} von {matching.length})</button>}
      {matching.length === 0 && <p className="rd-muted">Keine passende Leistung gefunden.</p>}
      <button type="button" className="rd-button rd-secondary" disabled={form.services.length >= MAX_SERVICES} onClick={() => { const id = `leistung-${crypto.randomUUID().slice(0, 8)}`; change({ services: [...form.services, { id, name: 'Neue Leistung', category: 'Eigene Leistungen', unit: 'pauschal', priceCents: null, active: true }] }); setCategory(''); setSearch('Neue Leistung'); setVisibleCount(12); }}><Plus size={17} />Leistung hinzufügen</button>
      {form.catalogue && <details className="rd-details"><summary>Hinweise zum importierten Katalog <ChevronDown size={16} /></summary><p className="rd-muted">{form.catalogue.title} · {form.catalogue.count} importierte Preispositionen</p><ul className="rd-import-notes">{form.catalogue.notes.map((note, i) => <li key={i}>{note}</li>)}</ul></details>}
    </fieldset>
    <fieldset disabled={busy} className="rd-panel"><div className="rd-section-heading"><div><h2>Vorgaben für Angebote</h2><p>Diese Angaben erscheinen auf Ihren neuen Angeboten.</p></div></div><div className="rd-fields"><label className="rd-field">Mehrwertsteuer<select value={form.taxPercent} onChange={e => change({ taxPercent: Number(e.target.value) as Settings['taxPercent'] })}><option value={19}>19 %</option><option value={7}>7 %</option><option value={0}>0 % – mit Steuerhinweis</option></select></label><label className="rd-field">Gültigkeit<select value={form.validityDays} onChange={e => change({ validityDays: Number(e.target.value) })}>{[7, 14, 30, 60, 90].map(n => <option key={n} value={n}>{n} Tage</option>)}{![7, 14, 30, 60, 90].includes(form.validityDays) && <option value={form.validityDays}>{form.validityDays} Tage</option>}</select></label>{form.taxPercent === 0 && <label className="rd-field rd-span">Steuerhinweis *<textarea rows={2} maxLength={300} value={form.taxNote} onChange={e => change({ taxNote: e.target.value })} placeholder="Den für Ihr Unternehmen zutreffenden Hinweis eingeben" /></label>}<label className="rd-field rd-span">Standardhinweis im PDF<textarea rows={3} maxLength={2000} value={form.note} onChange={e => change({ note: e.target.value })} /></label></div></fieldset>
    <fieldset disabled={busy} className="rd-panel"><div className="rd-section-heading"><div><h2>Firmendaten im PDF</h2><p>Logo und Markenfarben stammen von Ihrer bestehenden Website.</p></div></div><div className="rd-fields"><label className="rd-field">Firmenname<input value={form.company.name} maxLength={100} required onChange={e => change({ company: { ...form.company, name: e.target.value } })} /></label><label className="rd-field">Firmenanschrift<input value={form.company.address} maxLength={180} required onChange={e => change({ company: { ...form.company, address: e.target.value } })} /></label><label className="rd-field">E-Mail<input type="email" value={form.company.email} required onChange={e => change({ company: { ...form.company, email: e.target.value } })} /></label><label className="rd-field">Telefon<input type="tel" value={form.company.phone} maxLength={40} onChange={e => change({ company: { ...form.company, phone: e.target.value } })} /></label></div></fieldset>
    <div className="rd-settings-save">{error && <p className="rd-alert rd-error" role="alert">{error}</p>}{success && <p className="rd-alert rd-success" role="status"><Check size={18} />Gespeichert. Die neuen Werte sind sofort verfügbar.</p>}<button className="rd-button rd-primary" type="submit" disabled={busy || !ready}><Save size={18} />{busy ? 'Wird gespeichert …' : 'Einstellungen speichern'}</button><span>Gilt für neue Angebote.</span></div>
  </form>;
}
